#ifndef MODULARARITHMETICLIB_GLOBAL_H
#define MODULARARITHMETICLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULARARITHMETICLIB_LIBRARY)
#  define MODULARARITHMETICLIB_EXPORT Q_DECL_EXPORT
#else
#  define MODULARARITHMETICLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULARARITHMETICLIB_GLOBAL_H
